# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev
- staging
- uat
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '992d685f-fd16-4ac1-9fdf-fb6fdb6fbf23'
  imageRepository: 'timetodiagnosis'
  containerRegistry: 'whyze.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildNumber)-$(Build.SourceBranchName)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

extends:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/tags/dev') }}: 
    template: pipelines/TimeToDiagnosisDataTeam.yml@DevopsDataTeam
    parameters:
      GroupVariablesName: TimeToDiagnosisDevDataTeam

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/tags/staging') }}: 
    template: pipelines/TimeToDiagnosisDataTeam.yml@DevopsDataTeam
    parameters:
      GroupVariablesName: TimeToDiagnosisStagingDataTeam

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/tags/uat') }}: 
    template: pipelines/TimeToDiagnosisDataTeam.yml@DevopsDataTeam
    parameters:
      GroupVariablesName: TimeToDiagnosisUatDataTeam

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/tags/main') }}: 
    template: pipelines/TimeToDiagnosisDataTeam.yml@DevopsDataTeam
    parameters:
      GroupVariablesName: TimeToDiagnosisMainDataTeam