trigger:
- dev
- staging
- uat
- main

resources:
  repositories:
    - repository: DevopsDataTeam
      type: git
      name: DevopsDataTeam
      ref: refs/heads/dev
    - repository: self

pool:
  vmImageName: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: '992d685f-fd16-4ac1-9fdf-fb6fdb6fbf23'
  imageRepository: 'timetodiagnosis'
  containerRegistry: 'whyze.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildNumber)-$(Build.SourceBranchName)'
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: $[ replace(variables['System.PullRequest.TargetBranch'], 'refs/heads/', '') ]
  branch: '$(Build.SourceBranchName)'

extends:
  template: Pipelines/TimeToDiagnosisDataTeam.yml@DevopsDataTeam
  parameters:
    GroupVariablesName: ${{ format('TimeTodiagnosis_{0}', replace(variables.branch, 'refs/heads/', '')) }}


